title: "niyaz"
description: "phd researcher • human–ai interaction • augmented decision‑making"
url: "https://niyaz.me"
baseurl: ""
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
theme: minima
# We don't use built-in pagination; omit `paginate` to disable.
plugins: []
